### ISSUE TITLE
New Visualization: Seasonality of Community:

### ISSUE THREAD

**Issue by cdolfi** [oss-aspen/8Knot#204]
The seasonality of a community pertains to the different time based cycles on community activity. As described by @GregSutcliffe :
"

- [x] The day-of-week is useful to maintainers when thinking about things like when to post news, event invites etc, and when to be available/have office hours. #203 
- [ ] Day-of-year gives maintainers some way to adjust expectation for the coming time-horizon (i.e is it March? I might expect a dip in contribution then, and should not panic when it happens). Clearly this does not work for new projects (STL requires 2 time periods, so 2 years for this) #205 
- [ ] Not shown, but other seasonalities are possible. Hourly? Might reveal geographic information (i.e. if you get peaks at UTC +/-1 then you perhaps have an EU-centric community) #205 
- [ ] Non-periodic things can be done too, holidays are common. Also I once used an STL with "holidays" corresponding to release dates to analyse the effect of new releases on people upgrading from old versions."

The trend is useful to maintainers and contributors alike - the former will want to know how the project is faring, the latter will want to know if the project is alive and worth contributing too" 

Criteria for acceptance(to be updated): 
- [ ] Determine which of the following to measure, why, and how
- [ ] Create a small write up to go with the charts to make them accessible and understandable for all 
- [ ] Make conscious design choices that make it readable for people with non data science-statistics background 
- [ ] create a notebook with the visuals

**Comment by JamesKunstle** [comment]
We're currently doing this based on commit timestamps. Can we do this for issues, PRs, messages, etc?

**Comment by GregSutcliffe** [comment]
Unhelpfully, the answer here is "yes and no", IMO. But mostly, I think it's "yes"

Comments/reviews/etc - sure, you have a single defined timestamp to use. In particular for comments, seasonality across day-of-the-week or hour-of-the-day will tell you about the type & timezones of your community (people commenting during their working day are using it work, so could be a professional tool, whereas evening/weekends tend to be out-of-hours so a more hobbyist group is implied).

With Issues & PRs, though, you have 2 or 3 timestamps (create, close, and merge for PRs) and they all have a different interpretation in other metrics/visualisations. However here I think we're really interested in the question of "when are people active in my project?" and to that end, I think it doesn't really matter which you pick.

There's nuance in *who* is doing a type of work (e.g. users tend to open issues, devs tend to close them) which could be interesting when segmenting the community, but it's still "work done" and therefore relevant to this.

**Comment by cdolfi** [comment]
@GregSutcliffe Day of week makes sense to me (with some consideration on if its during one day in US EST for example but another day in the local time zone) , but with the lack of time zone stamps on non commit data I do not see how time of day data would be possible. Thoughts?

**Comment by GregSutcliffe** [comment]
So I'm guessing you're talking about the Augur data here, because the GitHub definitely has timestamps to the second. Here's a screen shot from https://api.github.com/repos/ansible/ansible/issues/80951:

![image](https://github.com/oss-aspen/8Knot/assets/827786/ed38c0e5-8b0b-4011-8c51-d4b3f2378d20)

As you can see, we've got `created_at`, `updated_at`, `closed_at`, and (because it's a PR) `merged_at`. You won't gte the last one for Issues, and you won't get `closed_at` if it's still open, so be sure to allow for missing values in your scripts :)

**Comment by sgoggins** [comment]
@GregSutcliffe : I'm going to open an issue referring to this one in Augur to convert our timestamp date types to timestamptz data types.

**Comment by cdolfi** [comment]
@sgoggins Awesome! Super excited about this
