### ISSUE TITLE
Add visualizations to pages -- Overview

### ISSUE THREAD

**Issue by JamesKunstle** [oss-aspen/8Knot#3]
Refer to the [miro board design](https://miro.com/app/board/uXjVORjEx30=/?invite_link_id=312825995436) for reference

The visualizations will be generated via jupyter notebook in the sandiego repo. An issue is to be created for each integration once the corresponding notebook is created.

Visualizations Required for Completion(short hand, refer to miro board for more details):

- [x] sandiego-rh/sandiego#136
- [x] sandiego-rh/sandiego#137
- [x] sandiego-rh/sandiego#138
- [x] Total number of commits - over time
- [ ] Stacked bar-plot of new PR's, Merged PRs, and unmerged PRs
- [x] #32
- [x] issues closed over time

**Comment by JamesKunstle** [comment]
Starting on adding "Total number of contributors over time" to Explorer

**Comment by JamesKunstle** [comment]
Have added "Total Number of Contributors over Time" and "Active/Drifting/Away" vizzes. Need to standardize format for them to be complete.

**Comment by JamesKunstle** [comment]
^^ done b @cdolfi
